#!/bin/sh

# format files with black and sort imports with isort
python -m black .
python -m isort .

# run jupytext sync to update all notebooks
python -m jupytext --sync --pipe black *.ipynb
python -m jupytext --pipe 'isort - --treat-comment-as-code "# %%" --float-to-top' *.ipynb
