#!/bin/sh

# format files with black and sort imports with isort
python -m black code
python -m isort code

# run jupytext sync to update all notebooks
python -m jupytext --sync --pipe black code/*.ipynb
python -m jupytext --pipe 'isort - --treat-comment-as-code "# %%" --float-to-top' code/*.ipynb
